
// export const CityImagesMap: Record<string, string> = {
// "aberdeen",
// "armagh",
// "bangor",
// "bath",
// "belfast",
// "birmingham",
// "bradford",
// "brighton and hove",
// "bristol",
// "cambridge",
// "canterbury",
// "cardiff",
// "carlisle",
// "chelmsford",
// "chester",
// "chichester",
// "city of london",
// "coventry",
// "derby",
// "derry",
// "dundee",
// "durham",
// "edinburgh",
// "ely",
// "exeter",
// "glasgow",
// "gloucester",
// "hereford",
// "inverness",
// "kingston upon hull",
// "lancaster",
// "leeds",
// "leicester",
// "lichfield",
// "lincoln",
// "lisburn",
// "liverpool",
// "london",
// "manchester",
// "newcastle upon tyne",
// "newport",
// "newry",
// "norwich",
// "nottingham",
// "oxford",
// "perth",
// "peterborough",
// "plymouth",
// "portsmouth",
// "preston",
// "ripon",
// "salford",
// "salisbury",
// "sheffield",
// "southampton",
// "st albans",
// "st davids",
// "stirling",
// "stoke-on-trent",
// "sunderland",
// "swansea",
// "truro",
// "wakefield",
// "wells",
// "westminster",
// "winchester",
// "wolverhampton",
// "worcester",
// "york"
// }
